// The 40 districts scored by the backend (config.LONDON_POSTCODE_DISTRICTS).
export const AREA_NAMES: Record<string, string> = {
  EC1A: "Barbican & St Bartholomew's",
  WC1A: "Holborn & Bloomsbury",
  SW1A: "Westminster & St James's",
  W1A: "Marylebone & Fitzrovia",
  N1: "Islington & King's Cross",
  N4: "Finsbury Park",
  NW1: "Camden Town & Regent's Park",
  NW3: "Hampstead & Belsize Park",
  E1: "Whitechapel & Spitalfields",
  E2: "Bethnal Green",
  SE1: "Southwark & Bermondsey",
  SE5: "Camberwell",
  SW4: "Clapham",
  SW8: "Vauxhall & Stockwell",
  W2: "Paddington & Bayswater",
  W6: "Hammersmith",
  NW6: "Kilburn & West Hampstead",
  N13: "Palmers Green",
  N21: "Winchmore Hill",
  EN1: "Enfield Town",
  E11: "Leytonstone & Wanstead",
  E17: "Walthamstow",
  IG1: "Ilford",
  RM1: "Romford",
  SE9: "Eltham",
  SE18: "Woolwich",
  DA1: "Dartford",
  BR1: "Bromley",
  BR3: "Beckenham",
  CR0: "Croydon",
  SM1: "Sutton",
  SW16: "Streatham",
  SW19: "Wimbledon",
  KT1: "Kingston upon Thames",
  TW1: "Twickenham",
  W5: "Ealing",
  W13: "West Ealing",
  UB1: "Southall",
  NW9: "Colindale & Kingsbury",
  HA1: "Harrow",
};

export const areaName = (district: string) => AREA_NAMES[district] ?? "";
